// ─────────────────────────────────────────────────
//  Stellar Pulse — Testnet Wallet Setup
//
//  Generates a fresh keypair, funds it via Friendbot,
//  adds a USDC trustline, and writes .env
// ─────────────────────────────────────────────────

import * as StellarSdk from "@stellar/stellar-sdk";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { logger } from "../src/utils/logger.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const HORIZON_URL  = "https://horizon-testnet.stellar.org";
const FRIENDBOT    = "https://friendbot.stellar.org";
const USDC_ISSUER  = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";
const USDC_CODE    = "USDC";

async function fundAndSetup() {
  logger.divider("STELLAR PULSE — TESTNET WALLET SETUP");

  // 1. Generate keypair
  const keypair = StellarSdk.Keypair.random();
  logger.success(`Generated keypair`);
  logger.info(`Public key:  ${keypair.publicKey()}`);
  logger.info(`Secret key:  ${keypair.secret()}`);

  // 2. Fund via Friendbot (gives 10,000 XLM on testnet)
  logger.info("Funding via Friendbot…");
  const fbRes = await fetch(`${FRIENDBOT}?addr=${keypair.publicKey()}`);
  if (!fbRes.ok) {
    throw new Error(`Friendbot failed: ${fbRes.status} ${await fbRes.text()}`);
  }
  logger.success("Funded with 10,000 XLM via Friendbot");

  // 3. Wait for account
  await new Promise((r) => setTimeout(r, 3000));

  // 4. Add USDC trustline
  const horizon  = new StellarSdk.Horizon.Server(HORIZON_URL);
  const account  = await horizon.loadAccount(keypair.publicKey());
  const usdcAsset = new StellarSdk.Asset(USDC_CODE, USDC_ISSUER);

  const trustTx = new StellarSdk.TransactionBuilder(account, {
    fee: "1000",
    networkPassphrase: StellarSdk.Networks.TESTNET,
  })
    .addOperation(
      StellarSdk.Operation.changeTrust({ asset: usdcAsset, limit: "100000" })
    )
    .setTimeout(30)
    .build();

  trustTx.sign(keypair);
  await horizon.submitTransaction(trustTx);
  logger.success("USDC trustline established");

  // 5. Request USDC from testnet faucet (if available)
  logger.info("Note: Fund your wallet with testnet USDC at https://testanchor.stellar.org/deposit");
  logger.info("Or use Stellar Laboratory: https://laboratory.stellar.org");

  // 6. Write .env file
  const envPath = path.join(__dirname, "../.env");
  const envContent = `# Generated by stellar-pulse fund script — ${new Date().toISOString()}

# ── Wallet Config ──────────────────────────────
PULSE_SECRET_KEY=${keypair.secret()}
PULSE_PUBLIC_KEY=${keypair.publicKey()}

# ── Network ────────────────────────────────────
STELLAR_NETWORK=testnet
STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015

# ── x402 Config ────────────────────────────────
X402_FACILITATOR_URL=https://www.x402.org/facilitator
X402_NETWORK=stellar:testnet

# ── Server Config ──────────────────────────────
PORT=4021
AGENT_PORT=4022

# ── Demo Mode ──────────────────────────────────
# Set to false to use real USDC from your wallet
DEMO_MODE=true

# ── Agent Loop ─────────────────────────────────
AGENT_LOOP_INTERVAL_SECONDS=30
`;

  fs.writeFileSync(envPath, envContent);
  logger.success(`.env written to ${envPath}`);

  logger.divider("SETUP COMPLETE");
  logger.info(`View your wallet: https://stellar.expert/explorer/testnet/account/${keypair.publicKey()}`);
  logger.info(`\nNext steps:`);
  logger.info(`  1. Fund with testnet USDC: https://testanchor.stellar.org`);
  logger.info(`  2. Run:  npm run dev`);
  logger.info(`  3. Open: http://localhost:4021`);
}

fundAndSetup().catch((err) => {
  logger.error("Setup failed", err instanceof Error ? err.message : err);
  process.exit(1);
});